# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11service_rpc.proto\")\n\x14lookupRequestMessage\x12\x11\n\tstockname\x18\x01 \x02(\t\"Z\n\x15lookupResponseMessage\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x11\n\tstockname\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"H\n\x13orderRequestMessage\x12\x11\n\tstockname\x18\x01 \x02(\t\x12\x10\n\x08quantity\x18\x02 \x02(\x05\x12\x0c\n\x04type\x18\x03 \x02(\t\"%\n\x14orderResponseMessage\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\"H\n\x13tradeRequestMessage\x12\x11\n\tstockname\x18\x01 \x02(\t\x12\x10\n\x08quantity\x18\x02 \x02(\x05\x12\x0c\n\x04type\x18\x03 \x02(\t\"A\n\x14tradeResponseMessage\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x1a\n\x12transaction_number\x18\x02 \x01(\x05\x32\x84\x01\n\x07\x43\x61talog\x12\x37\n\x06lookup\x12\x15.lookupRequestMessage\x1a\x16.lookupResponseMessage\x12@\n\x11\x62uy_or_sell_stock\x12\x14.orderRequestMessage\x1a\x15.orderResponseMessage2=\n\x05Order\x12\x34\n\x05trade\x12\x14.tradeRequestMessage\x1a\x15.tradeResponseMessage')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOOKUPREQUESTMESSAGE._serialized_start=21
  _LOOKUPREQUESTMESSAGE._serialized_end=62
  _LOOKUPRESPONSEMESSAGE._serialized_start=64
  _LOOKUPRESPONSEMESSAGE._serialized_end=154
  _ORDERREQUESTMESSAGE._serialized_start=156
  _ORDERREQUESTMESSAGE._serialized_end=228
  _ORDERRESPONSEMESSAGE._serialized_start=230
  _ORDERRESPONSEMESSAGE._serialized_end=267
  _TRADEREQUESTMESSAGE._serialized_start=269
  _TRADEREQUESTMESSAGE._serialized_end=341
  _TRADERESPONSEMESSAGE._serialized_start=343
  _TRADERESPONSEMESSAGE._serialized_end=408
  _CATALOG._serialized_start=411
  _CATALOG._serialized_end=543
  _ORDER._serialized_start=545
  _ORDER._serialized_end=606
# @@protoc_insertion_point(module_scope)
